changock:
  change-logs-scan-package:
    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.initializer
    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.updater
    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.ClientUpdater2ChangeLog
  trackIgnored: true
  startSystemVersion: start-vresion-01


  transactionable: false
